"""Render the benchmark's centerpiece tables from the saved result JSONs.

Reads data/model_results.json (scripts.modeling.models), data/generalization_results.json
(scripts.modeling.generalization) and data/model_c_coefficients.csv, and writes:
  - data/model_comparison.csv        the four-model x two-outcome grid, flat
  - article-assets/model-comparison.md  the three tables the article uses, as Markdown

  python -m scripts.modeling.comparison_table
"""
from __future__ import annotations

import json

import numpy as np
import pandas as pd

RESULTS = "data/model_results.json"
GEN = "data/generalization_results.json"
COEFS = "data/model_c_coefficients.csv"
CSV_OUT = "data/model_comparison.csv"
MD_OUT = "article-assets/model-comparison.md"

# pre-registered bar (build-log 2026-09-06, Week 2)
BAR_DELTA_R2 = 0.010
BAR_EFFECT_SD = 0.05

OUTCOME_LABEL = {"y_log_ratings": "Reach — log10(rating count)", "y_rating": "Reception — average rating"}
MODEL_LABEL = {
    "A": "A · baseline (genre, author fame, book age, series, publisher)",
    "B": "B · cover only (5 features, no controls)",
    "C": "C · controlled (A + 5 features)",
    "D": "D · CLIP catch-all (A + 100 image PCs)",
}
CLAIM_LABEL = {
    "single_focal_point": "Single focal point / hierarchy",
    "text_bg_contrast": "High text/background contrast",
    "typographic_simplicity": "Two-font max / simplicity",
    "thumbnail_legibility": "Thumbnail legibility",
    "low_clutter": "Low clutter",
}
# Sign of the coefficient the advice predicts, given how each feature is coded:
#   sal_gini up = more concentrated (advice: +)   title_contrast up = more contrast (+)
#   text_block_count up = LESS simple (advice: -)  legib_box_retention up = more legible (+)
#   clutter_z up = MORE cluttered (advice: -)
ADVICE_SIGN = {
    "single_focal_point": +1, "text_bg_contrast": +1, "typographic_simplicity": -1,
    "thumbnail_legibility": +1, "low_clutter": -1,
}
ADVICE_STR = {+1: "higher", -1: "lower"}


def _fmt(x, nd=4):
    return f"{x:+.{nd}f}" if x < 0 else f"{x:.{nd}f}"


def build():
    res = json.load(open(RESULTS))["results"]
    gen = json.load(open(GEN))["kfold_delta_r2"]
    coefs = pd.read_csv(COEFS)

    flat = []
    for y, blk in res.items():
        for m, r in blk["models"].items():
            flat.append({"outcome": y, "model": m, **r})
    pd.DataFrame(flat).to_csv(CSV_OUT, index=False)

    lines: list[str] = []
    lines.append("# Four-model benchmark — comparison tables\n")
    lines.append("_Generated by `python -m scripts.modeling.comparison_table`. "
                 "Held-out = 8,499 books by 3,671 authors not seen in training. "
                 "n = 42,344 English-language books._\n")

    # ---- Table 1: held-out fit ----
    lines.append("\n## 1. Held-out fit\n")
    lines.append("| Outcome | Model | k | R² train | R² test | RMSE test |")
    lines.append("|---|---|--:|--:|--:|--:|")
    for y, blk in res.items():
        for m in ["A", "B", "C", "D"]:
            r = blk["models"][m]
            lines.append(f"| {OUTCOME_LABEL[y]} | {MODEL_LABEL[m]} | {r['n_params']} | "
                         f"{r['r2_train']:.4f} | {r['r2_test']:.4f} | {r['rmse_test']:.4f} |")

    # ---- Table 2: the A -> C test ----
    lines.append("\n## 2. Does adding the 5 cover rules help? (A vs C)\n")
    lines.append(f"_Pre-registered bar (fixed before results): the rules \"matter\" if held-out "
                 f"ΔR² ≥ {BAR_DELTA_R2:.3f} on either outcome, or any single claim shows a "
                 f"correctly-signed standardized effect ≥ {BAR_EFFECT_SD:.2f}._\n")
    lines.append("| Outcome | Feature-block F (train) | ΔR² test (single split) | 95% CI | "
                 "ΔR² test (5-fold mean ± sd) | Sign stable? | Clears bar? |")
    lines.append("|---|--:|--:|--:|--:|:-:|:-:|")
    for y, blk in res.items():
        avc = blk["a_vs_c"]
        bt = avc["block_wald_f_train"]
        lo, hi = avc["delta_r2_test_ci95"]
        g = gen[y]
        clears = "**yes**" if abs(g["mean"]) >= BAR_DELTA_R2 else "no"
        lines.append(
            f"| {OUTCOME_LABEL[y]} | F({bt['df_num']},{bt['df_denom']})={bt['F']:.1f}, p={bt['p']:.1e} | "
            f"{avc['delta_r2_test']:+.5f} | [{lo:+.5f}, {hi:+.5f}] | "
            f"{g['mean']:+.5f} ± {g['sd']:.5f} | {'yes' if g['sign_stable'] else 'no'} | {clears} |")
    lines.append("\n_The training-set F is significant only because n is large; the held-out ΔR² "
                 "is the test the verdict rests on._\n")

    # ---- Table 2b: B vs C, D vs C ----
    lines.append("\n## 3. The other contrasts\n")
    lines.append("| Outcome | B (cover only) R² test | C R² test | D−C ΔR² test | D−A ΔR² test |")
    lines.append("|---|--:|--:|--:|--:|")
    for y, blk in res.items():
        b = blk["b_vs_c"]; d = blk["d_vs_c"]
        lines.append(f"| {OUTCOME_LABEL[y]} | {b['r2_test_B']:.4f} | {b['r2_test_C']:.4f} | "
                     f"{d['delta_r2_test_D_minus_C']:+.5f} | {d['delta_r2_test_D_minus_A']:+.5f} |")
    lines.append("\n_B → C: nearly all of the cover-only fit was genre/fame leaking through the "
                 "cover. D − C: even a full neural embedding adds < 1% over the 5 interpretable "
                 "features — the ceiling on any cover signal is also near zero._\n")

    # ---- Table 4: per-claim ----
    lines.append("\n## 4. Model C — per-claim standardized coefficients (HC3)\n")
    lines.append("| Claim | Advice says | β on reach (per SD) | β on rating (per SD) | Verdict |")
    lines.append("|---|:-:|--:|--:|---|")
    for claim in CLAIM_LABEL:
        rows = coefs[coefs.claim == claim]
        reach = rows[rows.outcome == "y_log_ratings"]
        rating = rows[rows.outcome == "y_rating"]
        # low_clutter carries one term (clutter_z); others one term each
        rb = reach.iloc[0]; ra = rating.iloc[0]
        def star(row):
            return "*" if row["p"] < 0.05 else ""
        rb_s = f"{rb['beta_per_sd']:+.4f}{star(rb)}"
        ra_s = f"{ra['beta_per_sd']:+.4f}{star(ra)}"
        want = ADVICE_SIGN[claim]
        sig = [r for r in (rb, ra) if r["p"] < 0.05]
        big = max(abs(rb["beta_per_sd"]), abs(ra["beta_per_sd"]))
        if not sig:
            verdict = "null"
        elif all(np.sign(r["beta_per_sd"]) == -want for r in sig):
            verdict = "**significant, wrong direction**" if big >= 0.015 else "sig. but trivial, wrong direction"
        elif all(np.sign(r["beta_per_sd"]) == want for r in sig):
            verdict = "right direction, trivial size"
        else:
            verdict = "mixed / see coefficients"
        lines.append(f"| {CLAIM_LABEL[claim]} | advice: {ADVICE_STR[want]} | {rb_s} | {ra_s} | {verdict} |")
    lines.append("\n_`*` = p < 0.05. β is in outcome units per 1 SD of the feature: for reach, "
                 "10^β − 1 is the % change in rating count. \"advice: higher/lower\" = the "
                 "direction the advice predicts for this coefficient given how the feature is coded._\n")

    open(MD_OUT, "w").writelines(l + "\n" for l in lines)
    print("".join(l + "\n" for l in lines))
    print(f"wrote {CSV_OUT} and {MD_OUT}")


if __name__ == "__main__":
    build()
